name: DAST Scan with OWASP ZAP

on: [push]

jobs:
  dast:
    runs-on: ubuntu-latest
    name: Run ZAP Baseline

    steps:
      - uses: actions/checkout@v4            # latest checkout
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Start PHP demo site
        run: php -S 127.0.0.1:8000 index.php &
      - run: sleep 5

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://127.0.0.1:8000/?name=test'
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'  # or drop this line
          cmd_options: '-a'
          fail_action: true            # break build on findings

      - name: Upload ZAP report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
