name: DAST Scan with OWASP ZAP

on: [push]

jobs:
  dast:
    runs-on: ubuntu-latest
    name: Run ZAP Baseline

    steps:
      - uses: actions/checkout@v4            # latest checkout
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Start PHP demo site
        run: php -S 127.0.0.1:8000 index.php &
      - run: sleep 5

      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.32.0

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0   # latest at time of writing
        with:
          target: 'http://127.0.0.1:8000/'
          fail_action: true          # fail the job on Medium/High alerts
          cmd_options: '-a'          # include alpha *active* + passive rules
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'

      - name: Upload ZAP report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html

